import { useEffect, useMemo, useRef, useState } from 'react'
import { redo, undo } from './commands'
import { exportPlayable, exportPlayablePWA } from './exportPlayable'
import { newLevel, openLevelFromFile, saveLevelToFile } from './levelIO'
import { spawnAsset, type AssetPayload } from './spawn'
import { useEditor } from './store'
import { runCSG } from './csg'
import { bakeAO, bakeAOMapUV2 } from '../engine/lightmapBake'
import { world } from '../engine/World'
import { listMaterials } from '../engine/materialAssets'
import { listAssetBlobs } from '../engine/assetStore'
import { getPrefabByName, instantiatePrefab, listPrefabs } from './prefabs'
import { assignMaterialAsset } from './materialCommands'
import { getPluginPaletteCommands } from './plugins'
import { isTypingTarget, matchesShortcutId } from './shortcuts'

/**
 * Command palette (Ctrl+Shift+P) — built-in commands + plugin-registered commands + asset search (Wave 12).
 * Plugin API lives in `src/editor/plugins.ts` and `window.lotus`.
 */

export type { PaletteCommand } from './plugins'
export {
  registerPlugin,
  registerNodeType,
  registerPanel,
  registerImporter,
  registerConsoleCommand,
  registerPanelCallback,
  installPlugin,
  loadUserPlugins,
} from './plugins'

const SPAWNABLES: Array<[string, AssetPayload]> = [
  ['Cube', { kind: 'mesh', geometry: 'box' }],
  ['Sphere', { kind: 'mesh', geometry: 'sphere' }],
  ['Point Light', { kind: 'light', type: 'PointLight' }],
  ['Camera', { kind: 'camera' }],
  ['Particles', { kind: 'particles' }],
  ['Foliage', { kind: 'foliage' }],
  ['Landscape', { kind: 'landscape' }],
  ['Trigger Volume', { kind: 'trigger' }],
  ['Player Start', { kind: 'playerstart' }],
]

interface PaletteEntry {
  label: string
  kind: 'command' | 'asset'
  run: () => void
}

function buildCommands(): PaletteEntry[] {
  const s = useEditor.getState()
  return [
    { label: 'Play In Editor', kind: 'command', run: () => s.startPlay('pie') },
    { label: 'Simulate', kind: 'command', run: () => s.startPlay('simulate') },
    { label: 'Stop', kind: 'command', run: () => s.stopPlay() },
    { label: 'New Level', kind: 'command', run: newLevel },
    { label: 'Open Level…', kind: 'command', run: openLevelFromFile },
    { label: 'Save Level', kind: 'command', run: saveLevelToFile },
    { label: 'Export Playable HTML', kind: 'command', run: () => exportPlayable() },
    { label: 'Export Playable HTML (PWA)', kind: 'command', run: exportPlayablePWA },
    { label: 'Undo', kind: 'command', run: undo },
    { label: 'Redo', kind: 'command', run: redo },
    { label: 'Toggle Game View', kind: 'command', run: () => s.toggleGameView() },
    { label: 'Open Console', kind: 'command', run: () => s.openConsole() },
    { label: 'Open Sequencer', kind: 'command', run: () => s.setBottomTab('sequencer') },
    { label: 'Open Blueprint Editor', kind: 'command', run: () => s.setBottomTab('blueprint') },
    { label: 'Open Behavior Tree Editor', kind: 'command', run: () => s.setBottomTab('bt') },
    { label: 'Open Data Editor', kind: 'command', run: () => s.setBottomTab('data') },
    { label: 'Open AI Copilot', kind: 'command', run: () => s.setBottomTab('ai') },
    { label: 'Open Debug Panel', kind: 'command', run: () => s.setBottomTab('debug') },
    { label: 'Open Plugin Manager', kind: 'command', run: () => s.setShowPluginManager(true) },
    { label: 'Project Settings…', kind: 'command', run: () => s.setShowProjectSettings(true) },
    { label: 'CSG: Union (2 selected)', kind: 'command', run: () => runCSG('union') },
    { label: 'CSG: Subtract (2 selected)', kind: 'command', run: () => runCSG('subtract') },
    { label: 'CSG: Intersect (2 selected)', kind: 'command', run: () => runCSG('intersect') },
    {
      label: 'Bake Reflection Probes',
      kind: 'command',
      run: () => {
        for (const a of world.actors.values()) if (a.type === 'ReflectionProbe') world.probeBakeQueue.push(a.id)
        s.setStatus('Probe bake queued')
      },
    },
    {
      label: 'Bake AO (approx)',
      kind: 'command',
      run: () => {
        s.setStatus('Baking AO (approx)…')
        void bakeAO(world.actors, {
          samples: 16,
          radius: 1,
          onProgress: (_done, _total, label) => useEditor.getState().setStatus(label),
        }).then((res) => {
          s.setStatus(
            res.ok
              ? `Baked AO (approx): ${res.actorsBaked} actors, ${res.verticesProcessed} verts`
              : `Bake AO failed: ${res.error ?? 'unknown'}`,
          )
          s.touch()
        })
      },
    },
    {
      label: 'Bake AO Map (UV2)',
      kind: 'command',
      run: () => {
        s.setStatus('AO Map Bake (UV2, approx)…')
        void bakeAOMapUV2(world.actors, {
          samples: 16,
          radius: 1,
          onProgress: (_done, _total, label) => useEditor.getState().setStatus(label),
        }).then((res) => {
          const warn = res.warnings?.length && res.ok ? ` · ${res.uv2AutoGenerated} uv2 auto-generated` : ''
          s.setStatus(
            res.ok
              ? `AO Map Bake (UV2, approx): ${res.meshesBaked} meshes, ${res.verticesProcessed} verts${warn}`
              : `AO map bake failed: ${res.error ?? 'unknown'}`,
          )
          s.touch()
        })
      },
    },
    ...SPAWNABLES.map(
      ([label, payload]): PaletteEntry => ({
        label: `Place: ${label}`,
        kind: 'command',
        run: () => spawnAsset(payload),
      }),
    ),
    ...getPluginPaletteCommands().map(
      (c): PaletteEntry => ({
        label: c.label,
        kind: 'command',
        run: c.run,
      }),
    ),
  ]
}

function buildAssetEntries(importNames: string[]): PaletteEntry[] {
  const s = useEditor.getState()
  const out: PaletteEntry[] = []

  for (const m of listMaterials()) {
    out.push({
      label: `Asset: Material / ${m.name}`,
      kind: 'asset',
      run: () => {
        const id = s.selectedId
        const actor = id ? world.actors.get(id) : null
        if (actor?.mesh) {
          assignMaterialAsset(actor.id, m.id)
          s.setStatus(`Assigned material: ${m.name}`)
        } else {
          s.setStatus(`Select a mesh actor to assign material: ${m.name}`)
        }
        s.setBottomTab('material')
      },
    })
  }

  for (const p of listPrefabs()) {
    out.push({
      label: `Asset: Prefab / ${p.name}`,
      kind: 'asset',
      run: () => {
        const prefab = getPrefabByName(p.name)
        if (!prefab) return
        const y = prefab.actors[0]?.transform.position[1] ?? 0
        instantiatePrefab(prefab, [0, y, 0])
        s.setStatus(`Spawned prefab: ${p.name}`)
      },
    })
  }

  for (const name of Object.keys(world.dataTables)) {
    out.push({
      label: `Asset: Data / ${name}`,
      kind: 'asset',
      run: () => {
        s.setBottomTab('data')
        s.setStatus(`Data asset: ${name}`)
      },
    })
  }

  for (const name of importNames) {
    out.push({
      label: `Asset: Import / ${name}`,
      kind: 'asset',
      run: () => {
        s.openContentDrawer()
        s.setStatus(`Imported asset: ${name} — open Content Drawer`)
      },
    })
  }

  return out
}

export function CommandPalette() {
  const [open, setOpen] = useState(false)
  const [query, setQuery] = useState('')
  const [sel, setSel] = useState(0)
  const [importNames, setImportNames] = useState<string[]>([])
  const inputRef = useRef<HTMLInputElement>(null)
  const sceneVersion = useEditor((s) => s.sceneVersion)

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (!isTypingTarget(e.target) && matchesShortcutId(e, 'panels.commandPalette')) {
        e.preventDefault()
        setOpen((o) => !o)
        setQuery('')
        setSel(0)
      }
      if (e.code === 'Escape') setOpen(false)
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [])

  useEffect(() => {
    if (open) {
      inputRef.current?.focus()
      void listAssetBlobs().then((blobs) => setImportNames(blobs.map((b) => b.name)))
    }
  }, [open])

  const entries = useMemo(
    () => [...buildCommands(), ...buildAssetEntries(importNames)],
    [open, sceneVersion, importNames],
  )
  const q = query.toLowerCase()
  const filtered = entries.filter((c) => c.label.toLowerCase().includes(q))

  if (!open) return null
  return (
    <div className="palette-backdrop" onMouseDown={() => setOpen(false)}>
      <div className="palette" onMouseDown={(e) => e.stopPropagation()}>
        <input
          ref={inputRef}
          value={query}
          placeholder="Type a command or asset…"
          onChange={(e) => {
            setQuery(e.target.value)
            setSel(0)
          }}
          onKeyDown={(e) => {
            e.stopPropagation()
            if (e.key === 'ArrowDown') setSel((x) => Math.min(filtered.length - 1, x + 1))
            if (e.key === 'ArrowUp') setSel((x) => Math.max(0, x - 1))
            if (e.key === 'Enter' && filtered[sel]) {
              setOpen(false)
              filtered[sel].run()
            }
            if (e.key === 'Escape') setOpen(false)
          }}
        />
        <div className="palette-list">
          {filtered.slice(0, 14).map((c, i) => (
            <button
              key={c.label}
              className={i === sel ? 'active' : ''}
              onMouseEnter={() => setSel(i)}
              onClick={() => {
                setOpen(false)
                c.run()
              }}
            >
              {c.kind === 'asset' ? '◆ ' : ''}
              {c.label}
            </button>
          ))}
          {filtered.length === 0 && <div className="panel-empty">No matching command or asset.</div>}
        </div>
      </div>
    </div>
  )
}