import * as THREE from 'three'
import { acceleratedRaycast, computeBoundsTree, disposeBoundsTree } from 'three-mesh-bvh'
import type { Actor } from './Actor'
import type { SerializedActor } from './types'
import type { AOBakeWorkerRequest, AOBakeWorkerResponse } from './lightmapBakeWorker'
import { unwrapUV2ForBake } from './xatlasUV2'

/**
 * Baked AO (approx) — hemisphere raycast ambient occlusion, not Lightmass.
 * Vertex path: writes per-vertex grayscale into geometry.color + material.vertexColors.
 * UV2 path: splats AO into a texture on uv2 and sets material.aoMap + aoMapIntensity.
 */

THREE.Mesh.prototype.raycast = acceleratedRaycast

export interface BakeAOOptions {
  samples?: number
  radius?: number
  /** 0–1 how strongly occlusion darkens vertices / AO map */
  strength?: number
  /** vertices processed per yield chunk (main-thread breathing room) */
  chunkSize?: number
  /** Run hemisphere raycasts in a Web Worker (default true). */
  useWorker?: boolean
  onProgress?: (done: number, total: number, label: string) => void
}

export interface BakeAOResult {
  ok: boolean
  actorsBaked: number
  verticesProcessed: number
  error?: string
}

export interface BakeAOMapOptions extends BakeAOOptions {
  /** AO map resolution (square). Default 256. */
  mapSize?: number
  /** aoMapIntensity on MeshStandardMaterial. Default 1. */
  aoMapIntensity?: number
  /** Auto-generate uv2 via xatlas/box projection when missing. Default true. */
  autoGenerateUV2?: boolean
  /** Attempt xatlas WASM unwrap before box projection fallback. Default true. */
  useXatlas?: boolean
}

export interface BakeAOMapResult {
  ok: boolean
  actorsBaked: number
  meshesBaked: number
  meshesSkipped: number
  uv2AutoGenerated: number
  verticesProcessed: number
  warnings?: string[]
  error?: string
}

export let aoBaking = false
export let lastAOBakeError: string | null = null
export let aoBakeProgress = { done: 0, total: 0, label: '' }

export let aoMapBaking = false
export let lastAOMapBakeError: string | null = null
export let aoMapBakeProgress = { done: 0, total: 0, label: '' }

const _pos = new THREE.Vector3()
const _normal = new THREE.Vector3()
const _rayDir = new THREE.Vector3()
const _rayOrigin = new THREE.Vector3()
const _tangent = new THREE.Vector3()
const _bitangent = new THREE.Vector3()
const _raycaster = new THREE.Raycaster()
const _bboxSize = new THREE.Vector3()

let bakePromise: Promise<BakeAOResult> | null = null
let bakeMapPromise: Promise<BakeAOMapResult> | null = null
let aoWorker: Worker | null = null
let aoWorkerReqId = 0

function getAOBakeWorker(): Worker {
  if (!aoWorker) {
    aoWorker = new Worker(new URL('./lightmapBakeWorker.ts', import.meta.url), { type: 'module' })
  }
  return aoWorker
}

function meshToOccluderPayload(mesh: THREE.Mesh) {
  const geo = mesh.geometry
  const pos = geo.attributes.position as THREE.BufferAttribute
  const idx = geo.index
  mesh.updateWorldMatrix(true, false)
  return {
    positions: new Float32Array(pos.array),
    indices: idx ? new Uint32Array(idx.array) : new Uint32Array(0),
    matrix: mesh.matrixWorld.toArray(),
  }
}

function meshToTargetPayload(mesh: THREE.Mesh) {
  const geo = mesh.geometry
  const pos = geo.attributes.position as THREE.BufferAttribute
  const norm = geo.attributes.normal as THREE.BufferAttribute
  const uv2 = geo.attributes.uv2 as THREE.BufferAttribute | undefined
  mesh.updateWorldMatrix(true, false)
  const normalMatrix = new THREE.Matrix3().getNormalMatrix(mesh.matrixWorld)
  return {
    positions: new Float32Array(pos.array),
    normals: new Float32Array(norm.array),
    uv2: uv2 ? new Float32Array(uv2.array) : undefined,
    matrix: mesh.matrixWorld.toArray(),
    normalMatrix: normalMatrix.toArray(),
  }
}

async function bakeAOInWorker(
  bakeActors: Actor[],
  occluders: THREE.Mesh[],
  opts: { samples: number; radius: number; strength: number; mapSize?: number; mode: 'bakeVertex' | 'bakeMap' },
): Promise<{ colors: Float32Array[]; maps?: Float32Array[] } | null> {
  try {
    const worker = getAOBakeWorker()
    const id = ++aoWorkerReqId
    const targets: AOBakeWorkerRequest['targets'] = []
    for (const actor of bakeActors) {
      for (const mesh of collectBakeMeshes(actor)) {
        if (!mesh.geometry.attributes.normal) mesh.geometry.computeVertexNormals()
        targets.push(meshToTargetPayload(mesh))
      }
    }
    const occluderPayload = occluders.map(meshToOccluderPayload)
    const req: AOBakeWorkerRequest = {
      type: opts.mode,
      id,
      samples: opts.samples,
      radius: opts.radius,
      strength: opts.strength,
      mapSize: opts.mapSize,
      targets,
      occluders: occluderPayload,
    }
    return await new Promise((resolve) => {
      const onMessage = (e: MessageEvent<AOBakeWorkerResponse>) => {
        if (e.data.id !== id || e.data.type !== opts.mode) return
        worker.removeEventListener('message', onMessage)
        if (e.data.ok) resolve({ colors: e.data.colors, maps: e.data.maps })
        else resolve(null)
      }
      worker.addEventListener('message', onMessage)
      worker.postMessage(req)
    })
  } catch {
    return null
  }
}

const hemisphereSamplesCache = new Map<number, THREE.Vector3[]>()

function getHemisphereSamples(count: number): THREE.Vector3[] {
  let cached = hemisphereSamplesCache.get(count)
  if (cached) return cached
  cached = []
  const golden = (1 + Math.sqrt(5)) / 2
  for (let i = 0; i < count; i++) {
    const t = (i + 0.5) / count
    const y = t
    const r = Math.sqrt(Math.max(0, 1 - y * y))
    const azimuth = (2 * Math.PI * i) / golden
    cached.push(new THREE.Vector3(Math.cos(azimuth) * r, y, Math.sin(azimuth) * r))
  }
  hemisphereSamplesCache.set(count, cached)
  return cached
}

function orientSampleToNormal(sample: THREE.Vector3, normal: THREE.Vector3, out: THREE.Vector3): THREE.Vector3 {
  if (Math.abs(normal.y) < 0.999) _tangent.set(0, 1, 0).cross(normal).normalize()
  else _tangent.set(1, 0, 0).cross(normal).normalize()
  _bitangent.crossVectors(normal, _tangent)
  out.set(0, 0, 0)
    .addScaledVector(_tangent, sample.x)
    .addScaledVector(_bitangent, sample.z)
    .addScaledVector(normal, sample.y)
  return out.normalize()
}

function isBakeGeometryActor(actor: Actor): boolean {
  if (actor.mobility !== 'static') return false
  if (actor.type === 'Landscape' && actor.landscapeProps?.weights) return false
  return (
    actor.type === 'StaticMesh' ||
    actor.type === 'CustomMesh' ||
    actor.type === 'ImportedMesh' ||
    actor.type === 'Landscape'
  )
}

function collectBakeMeshes(actor: Actor): THREE.Mesh[] {
  const meshes: THREE.Mesh[] = []
  actor.root.traverse((o) => {
    if (
      o instanceof THREE.Mesh &&
      !o.userData.isHelper &&
      !o.userData.isEditorOnly &&
      !o.userData.isParticles &&
      !o.userData.isLabel3D
    ) {
      meshes.push(o)
    }
  })
  return meshes
}

function collectAllOccluderMeshes(actors: Map<string, Actor>): THREE.Mesh[] {
  const meshes: THREE.Mesh[] = []
  for (const actor of actors.values()) {
    if (!isBakeGeometryActor(actor)) continue
    meshes.push(...collectBakeMeshes(actor))
  }
  return meshes
}

function ensureBVH(mesh: THREE.Mesh) {
  const geo = mesh.geometry
  if (!geo.attributes.position) return
  if (!geo.boundsTree) {
    geo.computeBoundsTree = computeBoundsTree
    geo.disposeBoundsTree = disposeBoundsTree
    geo.computeBoundsTree()
  }
}

function disposeBVH(mesh: THREE.Mesh) {
  const geo = mesh.geometry
  if (geo.boundsTree && geo.disposeBoundsTree) {
    geo.disposeBoundsTree()
  }
}

function enableVertexColors(mesh: THREE.Mesh) {
  const mats = Array.isArray(mesh.material) ? mesh.material : [mesh.material]
  for (const m of mats) {
    if (m instanceof THREE.MeshStandardMaterial) {
      m.vertexColors = true
      m.needsUpdate = true
    }
  }
}

function computeVertexOcclusion(
  worldPos: THREE.Vector3,
  worldNormal: THREE.Vector3,
  target: THREE.Mesh,
  occluders: THREE.Mesh[],
  sampleDirs: THREE.Vector3[],
  _radius: number,
  strength: number,
): number {
  void _radius
  _rayOrigin.copy(worldPos).addScaledVector(worldNormal, 0.002)
  let hits = 0
  for (const sample of sampleDirs) {
    orientSampleToNormal(sample, worldNormal, _rayDir)
    _raycaster.set(_rayOrigin, _rayDir)
    const intersections = _raycaster.intersectObjects(occluders, false)
    for (const hit of intersections) {
      if (hit.distance < 0.003 && hit.object === target) continue
      hits++
      break
    }
  }
  const occlusion = hits / sampleDirs.length
  return 1 - occlusion * strength
}

/** Simple box-projection uv2 for meshes without a second UV set. */
export function generateBoxProjectionUV2(geometry: THREE.BufferGeometry): boolean {
  const posAttr = geometry.attributes.position as THREE.BufferAttribute | undefined
  if (!posAttr?.count) return false
  if (!geometry.attributes.normal) geometry.computeVertexNormals()
  const normAttr = geometry.attributes.normal as THREE.BufferAttribute

  geometry.computeBoundingBox()
  const bbox = geometry.boundingBox
  if (!bbox) return false
  bbox.getSize(_bboxSize)
  const sx = _bboxSize.x || 1
  const sy = _bboxSize.y || 1
  const sz = _bboxSize.z || 1

  const uvs = new Float32Array(posAttr.count * 2)
  for (let i = 0; i < posAttr.count; i++) {
    const x = posAttr.getX(i)
    const y = posAttr.getY(i)
    const z = posAttr.getZ(i)
    const nx = normAttr.getX(i)
    const ny = normAttr.getY(i)
    const nz = normAttr.getZ(i)
    const ax = Math.abs(nx)
    const ay = Math.abs(ny)
    const az = Math.abs(nz)

    let u: number
    let v: number
    if (ax >= ay && ax >= az) {
      u = (z - bbox.min.z) / sz
      v = (y - bbox.min.y) / sy
    } else if (ay >= ax && ay >= az) {
      u = (x - bbox.min.x) / sx
      v = (z - bbox.min.z) / sz
    } else {
      u = (x - bbox.min.x) / sx
      v = (y - bbox.min.y) / sy
    }
    uvs[i * 2] = THREE.MathUtils.clamp(u, 0, 1)
    uvs[i * 2 + 1] = THREE.MathUtils.clamp(v, 0, 1)
  }

  geometry.setAttribute('uv2', new THREE.BufferAttribute(uvs, 2))
  geometry.attributes.uv2.needsUpdate = true
  return true
}

function ensureUV2(mesh: THREE.Mesh, autoGenerate: boolean): 'existing' | 'generated' | 'missing' {
  const geo = mesh.geometry
  if (geo.attributes.uv2?.count) return 'existing'
  if (!autoGenerate) return 'missing'
  return generateBoxProjectionUV2(geo) ? 'generated' : 'missing'
}

function finalizeAOMapBuffer(sum: Float32Array, count: Uint32Array, size: number): Float32Array {
  const out = new Float32Array(size * size)
  for (let i = 0; i < size * size; i++) {
    out[i] = count[i] > 0 ? sum[i] / count[i] : 1
  }

  for (let pass = 0; pass < 8; pass++) {
    let changed = false
    const next = out.slice()
    for (let y = 0; y < size; y++) {
      for (let x = 0; x < size; x++) {
        const i = y * size + x
        if (count[i] > 0) continue
        let s = 0
        let n = 0
        for (const [dx, dy] of [
          [-1, 0],
          [1, 0],
          [0, -1],
          [0, 1],
          [-1, -1],
          [1, -1],
          [-1, 1],
          [1, 1],
        ] as const) {
          const nx = x + dx
          const ny = y + dy
          if (nx < 0 || nx >= size || ny < 0 || ny >= size) continue
          const ni = ny * size + nx
          if (count[ni] > 0) {
            s += out[ni]
            n++
          }
        }
        if (n > 0) {
          next[i] = s / n
          changed = true
        }
      }
    }
    out.set(next)
    if (!changed) break
  }
  return out
}

function createAOMapTexture(pixels: Float32Array | number[], size: number): THREE.DataTexture {
  const arr = pixels instanceof Float32Array ? pixels : new Float32Array(pixels)
  const data = new Uint8Array(size * size * 3)
  for (let i = 0; i < size * size; i++) {
    const v = Math.round(THREE.MathUtils.clamp(arr[i] ?? 1, 0, 1) * 255)
    data[i * 3] = v
    data[i * 3 + 1] = v
    data[i * 3 + 2] = v
  }
  const tex = new THREE.DataTexture(data, size, size, THREE.RGBFormat)
  tex.colorSpace = THREE.NoColorSpace
  tex.needsUpdate = true
  return tex
}

function applyAOMap(mesh: THREE.Mesh, texture: THREE.DataTexture, intensity: number) {
  const mats = Array.isArray(mesh.material) ? mesh.material : [mesh.material]
  for (const m of mats) {
    if (m instanceof THREE.MeshStandardMaterial) {
      if (m.aoMap && m.aoMap !== texture) m.aoMap.dispose()
      m.aoMap = texture
      m.aoMapIntensity = intensity
      m.needsUpdate = true
    }
  }
}

export function applyVertexColors(mesh: THREE.Mesh, colors: Float32Array | number[]) {
  const arr = colors instanceof Float32Array ? colors : new Float32Array(colors)
  mesh.geometry.setAttribute('color', new THREE.BufferAttribute(arr, 3))
  mesh.geometry.attributes.color.needsUpdate = true
  enableVertexColors(mesh)
}

/** Re-apply serialized baked AO colors after level load / instantiate. */
export function applySerializedBakedAO(actor: Actor, sa: SerializedActor) {
  if (!sa.bakedAO) return
  actor.bakedAO = true
  if (!sa.bakedAOMeshes?.length) return
  const meshes = collectBakeMeshes(actor)
  sa.bakedAOMeshes.forEach((colors, i) => {
    const mesh = meshes[i]
    if (!mesh || !colors.length) return
    applyVertexColors(mesh, colors)
  })
}

/** Re-apply serialized AO map bake after level load / instantiate. */
export function applySerializedBakedAOMap(actor: Actor, sa: SerializedActor) {
  if (!sa.bakedAOMap) return
  actor.bakedAOMap = true
  actor.aoMapIntensity = sa.aoMapIntensity ?? 1
  actor.bakedAOMapSize = sa.bakedAOMapSize ?? 256
  if (!sa.bakedAOMapMeshes?.length) return
  const meshes = collectBakeMeshes(actor)
  const size = actor.bakedAOMapSize
  const intensity = actor.aoMapIntensity
  sa.bakedAOMapMeshes.forEach((pixels, i) => {
    const mesh = meshes[i]
    if (!mesh || !pixels.length) return
    if (!mesh.geometry.attributes.uv2) generateBoxProjectionUV2(mesh.geometry)
    const tex = createAOMapTexture(pixels, size)
    applyAOMap(mesh, tex, intensity)
  })
}

export function extractBakedAOMeshes(actor: Actor): number[][] | undefined {
  if (!actor.bakedAO) return undefined
  const meshes = collectBakeMeshes(actor)
  const out: number[][] = []
  for (const mesh of meshes) {
    const c = mesh.geometry.attributes.color
    if (c) out.push(Array.from(c.array as ArrayLike<number>))
    else out.push([])
  }
  return out.some((a) => a.length) ? out : undefined
}

export function extractBakedAOMapMeshes(actor: Actor): number[][] | undefined {
  if (!actor.bakedAOMap) return undefined
  const meshes = collectBakeMeshes(actor)
  const out: number[][] = []
  for (const mesh of meshes) {
    const mats = Array.isArray(mesh.material) ? mesh.material : [mesh.material]
    const mat = mats.find(
      (m) => m instanceof THREE.MeshStandardMaterial && m.aoMap instanceof THREE.DataTexture,
    ) as THREE.MeshStandardMaterial | undefined
    const tex = mat?.aoMap as THREE.DataTexture | undefined
    if (!tex?.image?.data) {
      out.push([])
      continue
    }
    const w = tex.image.width
    const h = tex.image.height
    const arr = tex.image.data as Uint8Array
    const pixels: number[] = []
    for (let i = 0; i < w * h; i++) pixels.push((arr[i * 3] ?? 255) / 255)
    out.push(pixels)
  }
  return out.some((a) => a.length) ? out : undefined
}

function yieldChunk(): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, 0))
}

/**
 * Bake approximate ambient occlusion into vertex colors for static mesh actors.
 * Label: "Baked AO (approx)" — not Lightmass.
 */
export async function bakeAO(
  actors: Map<string, Actor>,
  opts: BakeAOOptions = {},
): Promise<BakeAOResult> {
  if (bakePromise) return bakePromise

  const samples = Math.max(4, Math.min(64, opts.samples ?? 16))
  const radius = Math.max(0.05, opts.radius ?? 1)
  const strength = Math.max(0, Math.min(1, opts.strength ?? 0.85))
  const chunkSize = Math.max(32, opts.chunkSize ?? 256)
  const useWorker = opts.useWorker !== false
  const onProgress = opts.onProgress

  bakePromise = (async (): Promise<BakeAOResult> => {
    aoBaking = true
    lastAOBakeError = null
    aoBakeProgress = { done: 0, total: 0, label: 'Collecting geometry…' }
    onProgress?.(0, 1, aoBakeProgress.label)

    const bakeActors = [...actors.values()].filter(isBakeGeometryActor)
    const occluders = collectAllOccluderMeshes(actors)

    if (!occluders.length) {
      lastAOBakeError = 'No static mesh geometry to bake'
      aoBaking = false
      bakePromise = null
      return { ok: false, actorsBaked: 0, verticesProcessed: 0, error: lastAOBakeError }
    }

    for (const mesh of occluders) ensureBVH(mesh)

    let totalVerts = 0
    for (const actor of bakeActors) {
      for (const mesh of collectBakeMeshes(actor)) {
        totalVerts += mesh.geometry.attributes.position?.count ?? 0
      }
    }

    aoBakeProgress = { done: 0, total: totalVerts, label: 'Baking AO (approx)…' }
    onProgress?.(0, totalVerts, aoBakeProgress.label)

    let processed = 0
    let actorsBaked = 0

    try {
      if (useWorker) {
        aoBakeProgress = { done: 0, total: totalVerts, label: 'Baking AO (approx, worker)…' }
        onProgress?.(0, totalVerts, aoBakeProgress.label)
        const workerResult = await bakeAOInWorker(bakeActors, occluders, {
          samples,
          radius,
          strength,
          mode: 'bakeVertex',
        })
        if (workerResult) {
          let meshIdx = 0
          for (const actor of bakeActors) {
            const targets = collectBakeMeshes(actor)
            if (!targets.length) continue
            for (const target of targets) {
              const colors = workerResult.colors[meshIdx++]
              if (colors?.length) {
                applyVertexColors(target, colors)
                processed += colors.length / 3
              }
            }
            actor.bakedAO = true
            actorsBaked++
          }
          aoBakeProgress = { done: totalVerts, total: totalVerts, label: 'Baked AO (approx) complete' }
          onProgress?.(totalVerts, totalVerts, aoBakeProgress.label)
          return { ok: true, actorsBaked, verticesProcessed: processed }
        }
      }

      const sampleDirs = getHemisphereSamples(samples)
      _raycaster.far = radius
      _raycaster.near = 0.0001
      _raycaster.firstHitOnly = true
      let vertsSinceYield = 0

      for (const actor of bakeActors) {
        const targets = collectBakeMeshes(actor)
        if (!targets.length) continue

        for (const target of targets) {
          const geo = target.geometry
          const posAttr = geo.attributes.position as THREE.BufferAttribute | undefined
          const normAttr = geo.attributes.normal as THREE.BufferAttribute | undefined
          if (!posAttr?.count) continue

          if (!normAttr) geo.computeVertexNormals()

          const colors = new Float32Array(posAttr.count * 3)
          target.updateWorldMatrix(true, false)
          const normalMatrix = new THREE.Matrix3().getNormalMatrix(target.matrixWorld)

          for (let vi = 0; vi < posAttr.count; vi++) {
            _pos.fromBufferAttribute(posAttr, vi).applyMatrix4(target.matrixWorld)
            _normal.fromBufferAttribute(geo.attributes.normal as THREE.BufferAttribute, vi)
            _normal.applyMatrix3(normalMatrix).normalize()

            const shade = computeVertexOcclusion(
              _pos,
              _normal,
              target,
              occluders,
              sampleDirs,
              radius,
              strength,
            )
            colors[vi * 3] = shade
            colors[vi * 3 + 1] = shade
            colors[vi * 3 + 2] = shade

            processed++
            vertsSinceYield++
            if (vertsSinceYield >= chunkSize) {
              vertsSinceYield = 0
              aoBakeProgress = {
                done: processed,
                total: totalVerts,
                label: `Baked AO (approx): ${actor.name}`,
              }
              onProgress?.(processed, totalVerts, aoBakeProgress.label)
              await yieldChunk()
            }
          }

          applyVertexColors(target, colors)
        }

        actor.bakedAO = true
        actorsBaked++
      }

      aoBakeProgress = { done: totalVerts, total: totalVerts, label: 'Baked AO (approx) complete' }
      onProgress?.(totalVerts, totalVerts, aoBakeProgress.label)
      return { ok: true, actorsBaked, verticesProcessed: processed }
    } catch (err) {
      lastAOBakeError = err instanceof Error ? err.message : String(err)
      return { ok: false, actorsBaked, verticesProcessed: processed, error: lastAOBakeError }
    } finally {
      for (const mesh of occluders) disposeBVH(mesh)
      aoBaking = false
      bakePromise = null
    }
  })()

  return bakePromise
}

/**
 * Bake approximate AO into uv2 textures (aoMap) for static mesh actors.
 * Label: "AO Map Bake (UV2, approx)" — not Lightmass.
 */
export async function bakeAOMapUV2(
  actors: Map<string, Actor>,
  opts: BakeAOMapOptions = {},
): Promise<BakeAOMapResult> {
  if (bakeMapPromise) return bakeMapPromise

  const samples = Math.max(4, Math.min(64, opts.samples ?? 16))
  const radius = Math.max(0.05, opts.radius ?? 1)
  const strength = Math.max(0, Math.min(1, opts.strength ?? 0.85))
  const chunkSize = Math.max(32, opts.chunkSize ?? 256)
  const mapSize = Math.max(64, Math.min(1024, opts.mapSize ?? 256))
  const aoMapIntensity = Math.max(0, Math.min(2, opts.aoMapIntensity ?? 1))
  const autoGenerateUV2 = opts.autoGenerateUV2 !== false
  const useXatlas = opts.useXatlas !== false
  const useWorker = opts.useWorker !== false
  const onProgress = opts.onProgress

  bakeMapPromise = (async (): Promise<BakeAOMapResult> => {
    aoMapBaking = true
    lastAOMapBakeError = null
    aoMapBakeProgress = { done: 0, total: 0, label: 'Collecting geometry…' }
    onProgress?.(0, 1, aoMapBakeProgress.label)

    const bakeActors = [...actors.values()].filter(isBakeGeometryActor)
    const occluders = collectAllOccluderMeshes(actors)
    const warnings: string[] = []

    if (!occluders.length) {
      lastAOMapBakeError = 'No static mesh geometry to bake'
      aoMapBaking = false
      bakeMapPromise = null
      return {
        ok: false,
        actorsBaked: 0,
        meshesBaked: 0,
        meshesSkipped: 0,
        uv2AutoGenerated: 0,
        verticesProcessed: 0,
        error: lastAOMapBakeError,
      }
    }

    for (const mesh of occluders) ensureBVH(mesh)

    let totalVerts = 0
    for (const actor of bakeActors) {
      for (const mesh of collectBakeMeshes(actor)) {
        totalVerts += mesh.geometry.attributes.position?.count ?? 0
      }
    }

    aoMapBakeProgress = { done: 0, total: totalVerts, label: 'AO Map Bake (UV2, approx)…' }
    onProgress?.(0, totalVerts, aoMapBakeProgress.label)

    let processed = 0
    let actorsBaked = 0
    let meshesBaked = 0
    let meshesSkipped = 0
    let uv2AutoGenerated = 0

    try {
      if (useWorker) {
        for (const actor of bakeActors) {
          for (const target of collectBakeMeshes(actor)) {
            if (!target.geometry.attributes.uv2 && autoGenerateUV2) {
              if (useXatlas) await unwrapUV2ForBake(target.geometry)
              else generateBoxProjectionUV2(target.geometry)
              uv2AutoGenerated++
            }
          }
        }
        const workerResult = await bakeAOInWorker(bakeActors, occluders, {
          samples,
          radius,
          strength,
          mapSize,
          mode: 'bakeMap',
        })
        if (workerResult?.maps) {
          let meshIdx = 0
          for (const actor of bakeActors) {
            const targets = collectBakeMeshes(actor)
            let actorHadBake = false
            for (const target of targets) {
              const pixels = workerResult.maps![meshIdx]
              const colors = workerResult.colors[meshIdx]
              meshIdx++
              if (!pixels?.length) {
                meshesSkipped++
                continue
              }
              const tex = createAOMapTexture(pixels, mapSize)
              applyAOMap(target, tex, aoMapIntensity)
              if (colors?.length) applyVertexColors(target, colors)
              meshesBaked++
              actorHadBake = true
              processed += colors?.length ? colors.length / 3 : 0
            }
            if (actorHadBake) {
              actor.bakedAOMap = true
              actor.bakedAOMapSize = mapSize
              actor.aoMapIntensity = aoMapIntensity
              actorsBaked++
            }
          }
          if (meshesBaked) {
            aoMapBakeProgress = {
              done: totalVerts,
              total: totalVerts,
              label: 'AO Map Bake (UV2, approx) complete',
            }
            onProgress?.(totalVerts, totalVerts, aoMapBakeProgress.label)
            return {
              ok: true,
              actorsBaked,
              meshesBaked,
              meshesSkipped,
              uv2AutoGenerated,
              verticesProcessed: processed,
              warnings: uv2AutoGenerated
                ? [`${uv2AutoGenerated} mesh(es): uv2 generated (xatlas/box approx)`]
                : undefined,
            }
          }
        }
      }

      const sampleDirs = getHemisphereSamples(samples)
      _raycaster.far = radius
      _raycaster.near = 0.0001
      _raycaster.firstHitOnly = true
      let vertsSinceYield = 0

      for (const actor of bakeActors) {
        const targets = collectBakeMeshes(actor)
        if (!targets.length) continue

        let actorHadBake = false

        for (const target of targets) {
          const geo = target.geometry
          const posAttr = geo.attributes.position as THREE.BufferAttribute | undefined
          if (!posAttr?.count) {
            meshesSkipped++
            warnings.push(`${actor.name}: mesh has no positions — skipped`)
            continue
          }

          let uv2State = ensureUV2(target, false)
          if (uv2State === 'missing' && autoGenerateUV2) {
            if (useXatlas) {
              const unwrap = await unwrapUV2ForBake(target.geometry)
              uv2State = unwrap.method === 'failed' ? 'missing' : unwrap.method === 'existing' ? 'existing' : 'generated'
            } else {
              uv2State = generateBoxProjectionUV2(target.geometry) ? 'generated' : 'missing'
            }
          }
          if (uv2State === 'missing') {
            meshesSkipped++
            warnings.push(`${actor.name}: no uv2 and box projection failed — skipped`)
            continue
          }
          if (uv2State === 'generated') {
            uv2AutoGenerated++
            warnings.push(`${actor.name}: uv2 auto-generated via box projection (approx)`)
          }

          if (!geo.attributes.normal) geo.computeVertexNormals()
          const uv2Attr = geo.attributes.uv2 as THREE.BufferAttribute

          const sum = new Float32Array(mapSize * mapSize)
          const count = new Uint32Array(mapSize * mapSize)

          target.updateWorldMatrix(true, false)
          const normalMatrix = new THREE.Matrix3().getNormalMatrix(target.matrixWorld)

          for (let vi = 0; vi < posAttr.count; vi++) {
            _pos.fromBufferAttribute(posAttr, vi).applyMatrix4(target.matrixWorld)
            _normal.fromBufferAttribute(geo.attributes.normal as THREE.BufferAttribute, vi)
            _normal.applyMatrix3(normalMatrix).normalize()

            const shade = computeVertexOcclusion(
              _pos,
              _normal,
              target,
              occluders,
              sampleDirs,
              radius,
              strength,
            )

            const u = uv2Attr.getX(vi)
            const v = uv2Attr.getY(vi)
            const tx = THREE.MathUtils.clamp(Math.floor(u * mapSize), 0, mapSize - 1)
            const ty = THREE.MathUtils.clamp(Math.floor(v * mapSize), 0, mapSize - 1)
            const ti = ty * mapSize + tx
            sum[ti] += shade
            count[ti]++

            processed++
            vertsSinceYield++
            if (vertsSinceYield >= chunkSize) {
              vertsSinceYield = 0
              aoMapBakeProgress = {
                done: processed,
                total: totalVerts,
                label: `AO Map Bake (UV2, approx): ${actor.name}`,
              }
              onProgress?.(processed, totalVerts, aoMapBakeProgress.label)
              await yieldChunk()
            }
          }

          const pixels = finalizeAOMapBuffer(sum, count, mapSize)
          const tex = createAOMapTexture(pixels, mapSize)
          applyAOMap(target, tex, aoMapIntensity)
          meshesBaked++
          actorHadBake = true
        }

        if (actorHadBake) {
          actor.bakedAOMap = true
          actor.bakedAOMapSize = mapSize
          actor.aoMapIntensity = aoMapIntensity
          actorsBaked++
        }
      }

      if (!meshesBaked) {
        lastAOMapBakeError = 'No meshes could be baked — missing uv2 on all targets'
        return {
          ok: false,
          actorsBaked: 0,
          meshesBaked: 0,
          meshesSkipped,
          uv2AutoGenerated,
          verticesProcessed: processed,
          warnings,
          error: lastAOMapBakeError,
        }
      }

      aoMapBakeProgress = {
        done: totalVerts,
        total: totalVerts,
        label: 'AO Map Bake (UV2, approx) complete',
      }
      onProgress?.(totalVerts, totalVerts, aoMapBakeProgress.label)
      return {
        ok: true,
        actorsBaked,
        meshesBaked,
        meshesSkipped,
        uv2AutoGenerated,
        verticesProcessed: processed,
        warnings: warnings.length ? warnings : undefined,
      }
    } catch (err) {
      lastAOMapBakeError = err instanceof Error ? err.message : String(err)
      return {
        ok: false,
        actorsBaked,
        meshesBaked,
        meshesSkipped,
        uv2AutoGenerated,
        verticesProcessed: processed,
        warnings,
        error: lastAOMapBakeError,
      }
    } finally {
      for (const mesh of occluders) disposeBVH(mesh)
      aoMapBaking = false
      bakeMapPromise = null
    }
  })()

  return bakeMapPromise
}